# config/routes.yaml

# the "app_lucky_number" route name is not important yet
index:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
    
create_skill:
    path: /skill/create
    controller: App\Controller\SkillsController::create
    
edit_skill:
    path: /skill/edit/{id}
    controller: App\Controller\SkillsController::edit
    
valid_skill:
    path: /skill/validate
    controller: App\Controller\SkillsController::valid